### Get Host Data
GET http://localhost:3001/snmp/172.16.8.2
Content-Type: application/json

### Custom SNMP Request
GET http://localhost:3001/snmp/custom
  ?ip=172.16.8.2
  &community=v1a1pe@RNPcom91
  &oid=1.3.6.1.2.1.1.5
Content-Type: application/json

# {
#   ip: "172.16.8.2",
#   community: "v1a1pe@RNPcom91",
#   oid: "1.3.6.1.2.1.1.5"
# }

### Custom SNMP Request
GET http://localhost:3001/snmp/custom?ip=172.16.8.2&community=v1a1pe@RNPcom91&oid=1.3.6.1.2.1.1.5
Content-Type: application/json
